[build]
builder = "dockerfile"

[deploy]
startCommand = "node apps/seat-api/dist/main"
healthcheckPath = "/seats"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
